export const PAGINATION: { [key: string]: any } = {
  DEFAULT_CURRENT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 24,
  DEFAULT_TOTAL_ITEM: 0,
  DEFAULT_PAGE_SIZE_OPTIONS: ["24", "50", "100", "150", "200"],
  DEFAULT_TOTAL_PAGE: 1,
}

